spring:
  web:
    resources:
      # 정적 리소스 위치 설정
      static-locations: classpath:/static/vue/
  # h2 db 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=LEGACY
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # jpa 설정
  jpa:
    # jpa가 수행하는 sql를 볼 수 있음.
    show-sql: true
    properties:
      hibernate:
        # 보여지는 쿼리를 예쁘게 보여준다.
        format_sql: true

